[package]
name = "back_back"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.7"
actix-cors = "0.6"
actix-multipart = "0.6"
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

