[package]
name = "back_back"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"        
actix-files = "0.6"      # for file handling
tempfile = "3.3"         # for temporary files
futures-util = "0.3"     # for `StreamExt`
actix-cors = "0.6"
